---
# **Crime data Exploratory Data Analysis: Pre-processing**
---

**1. Import Libraries**

In [57]:
import pandas as pd
import numpy as np
import glob # to import multiple files at once

**2. Load and Explore the Data**

City of London

In [ ]:
# import all the city of london data in one dataframe

city_files = sorted(glob.glob("data/*/*city-of-london-street.csv")) # glob.glob returns a list of file paths matching the pattern, sorted to maintain order
city = pd.concat([pd.read_csv(file) for file in city_files], ignore_index=True) # ignore_index to reset the index after concatenation

In [ ]:
city.info() # check the info of the dataframe to understand the data types and null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19577 entries, 0 to 19576
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Crime ID               19042 non-null  object
 1   Month                  19577 non-null  object
 2   Reported by            19577 non-null  object
 3   Falls within           19577 non-null  object
 4   Longitude              17937 non-null  float64
 5   Latitude               17937 non-null  float64
 6   Location               19577 non-null  object
 7   LSOA code              17937 non-null  object
 8   LSOA name              17937 non-null  object
 9   Crime type             19577 non-null  object
 10  Last outcome category  19042 non-null  object
 11  Context                0 non-null      float64
dtypes: float64(3), object(9)
memory usage: 1.8+ MB

In [ ]:
display(city.isnull().sum(), round(city.isnull().mean(), 2)) # check the number of null values in each column and the percentage of null values in each column

Crime ID                   535
Month                        0
Reported by                  0
Falls within                 0
Longitude                 1640
Latitude                  1640
Location                     0
LSOA code                 1640
LSOA name                 1640
Crime type                   0
Last outcome category      535
Context                  19577
dtype: int64

Crime ID                 0.03
Month                    0.00
Reported by              0.00
Falls within             0.00
Longitude                0.08
Latitude                 0.08
Location                 0.00
LSOA code                0.08
LSOA name                0.08
Crime type               0.00
Last outcome category    0.03
Context                  1.00
dtype: float64

In [ ]:
# remove context column as they have no values
city = city.drop(columns=["Context"], inplace=False)

KeyError: "['Context'] not found in axis"

In [ ]:
city.columns # check if the column has been removed

Index(['Crime ID', 'Month', 'Reported by', 'Falls within', 'Longitude',
       'Latitude', 'Location', 'LSOA code', 'LSOA name', 'Crime type',
       'Last outcome category'],
      dtype='object')

In [ ]:
# drop rows with null values in lsoa name column (location data)
city = city.dropna(subset=["LSOA name"], inplace=False)
city.isnull().sum()

Crime ID                 457
Month                      0
Reported by                0
Falls within               0
Longitude                  0
Latitude                   0
Location                   0
LSOA code                  0
LSOA name                  0
Crime type                 0
Last outcome category    457
dtype: int64

In [72]:
# drop rows with null crime id and last outcome category

city = city.dropna(subset=["Crime ID", "Last outcome category"], inplace=False)
city.isnull().sum()

Crime ID                 0
Month                    0
Reported by              0
Falls within             0
Longitude                0
Latitude                 0
Location                 0
LSOA code                0
LSOA name                0
Crime type               0
Last outcome category    0
dtype: int64

In [ ]:
# Adding all the city of london data in one dataframe

city1 = pd.read_csv("data/2024-01/2024-01-city-of-london-street.csv")
city1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 734 entries, 0 to 733
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Crime ID               722 non-null    object
 1   Month                  734 non-null    object
 2   Reported by            734 non-null    object
 3   Falls within           734 non-null    object
 4   Longitude              657 non-null    float64
 5   Latitude               657 non-null    float64
 6   Location               734 non-null    object
 7   LSOA code              657 non-null    object
 8   LSOA name              657 non-null    object
 9   Crime type             734 non-null    object
 10  Last outcome category  722 non-null    object
 11  Context                0 non-null      float64
dtypes: float64(3), object(9)
memory usage: 68.9+ KB

In [ ]:
city = pd.read_csv("data/2024-01/2024-01-city-of-london-street.csv")
metro = pd.read_csv("data/2024-01/2024-01-metropolitan-street.csv")
surrey = pd.read_csv("data/2024-01/2024-01-surrey-street.csv")
thames = pd.read_csv("data/2024-01/2024-01-thames-valley-street.csv")
wmids = pd.read_csv("data/2024-01/2024-01-west-midlands-street.csv")
wyork = pd.read_csv("data/2024-01/2024-01-west-yorkshire-street.csv")

In [ ]:
city.head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,e7b720d0e1302d2d06db7b28b29132eb194864d44d7921...,2024-01,City of London Police,City of London Police,-0.106220,51.518275,On or near B500,E01000916,Camden 027B,Theft from the person,Investigation complete; no suspect identified,NaN
1,e60a5ac62a80e866453254474137c3206417422c62f0c0...,2024-01,City of London Police,City of London Police,-0.107682,51.517786,On or near B521,E01000917,Camden 027C,Other theft,Investigation complete; no suspect identified,NaN
2,986f618142ec52b7f254e4b0549da2f17ceeb0e130db6c...,2024-01,City of London Police,City of London Police,-0.111596,51.518281,On or near Chancery Lane,E01000914,Camden 028B,Other theft,Investigation complete; no suspect identified,NaN
3,05dc27a88748356f6d59b0bd1389710ebfb42b37e565af...,2024-01,City of London Police,City of London Police,-0.111596,51.518281,On or near Chancery Lane,E01000914,Camden 028B,Theft from the person,Status update unavailable,NaN
4,373d78e2ccec5d05a547cd4bee19045a9e050042a0e6e7...,2024-01,City of London Police,City of London Police,-0.112096,51.515942,On or near Nightclub,E01000914,Camden 028B,Theft from the person,Investigation complete; no suspect identified,NaN

In [ ]:
metro.head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,e5b3ed0375b796067eb668f37a18094cce300bdbd5446c...,2024-01,Metropolitan Police Service,Metropolitan Police Service,-0.552328,50.853155,On or near Queen Street,E01031392,Arun 001C,Other theft,Unable to prosecute suspect,NaN
1,d5d46efe4a74b2fdf87f28f7c89c4d7534c80d4150f58f...,2024-01,Metropolitan Police Service,Metropolitan Police Service,-0.666558,50.848940,On or near Northfields Lane,E01031396,Arun 003D,Violence and sexual offences,Status update unavailable,NaN
2,8ee491f5ebeda54bda879fed602d2f308bfd8abf4b59f7...,2024-01,Metropolitan Police Service,Metropolitan Police Service,-0.657460,50.787270,On or near Kingsmead,E01031419,Arun 015C,Violence and sexual offences,Status update unavailable,NaN
3,318e91d9bd9ad081bb348b8c743236365c9178eb60229d...,2024-01,Metropolitan Police Service,Metropolitan Police Service,0.876815,51.147655,On or near Parking Area,E01034986,Ashford 005G,Violence and sexual offences,Status update unavailable,NaN
4,8ec949bf76f02215ad73b489ff502ab32101b0834b49fc...,2024-01,Metropolitan Police Service,Metropolitan Police Service,0.884060,51.110654,On or near Southdown Close,E01034989,Ashford 010G,Violence and sexual offences,Status update unavailable,NaN

In [ ]:
surrey.head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,a21e838add64c3345496907f148dd922f876219f984d29...,2024-01,Surrey Police,Surrey Police,-0.101292,51.51477,On or near Amen Court,E01032739,City of London 001F,Violence and sexual offences,Unable to prosecute suspect,NaN
1,6f797cbcab36f245e49e9e69da33e8818669fd81f7df27...,2024-01,Surrey Police,Surrey Police,-0.101292,51.51477,On or near Amen Court,E01032739,City of London 001F,Other theft,Unable to prosecute suspect,NaN
2,fc789288d77042ae6d8082da50db413b68d04610b2ca1d...,2024-01,Surrey Police,Surrey Police,-0.101292,51.51477,On or near Amen Court,E01032739,City of London 001F,Other theft,Investigation complete; no suspect identified,NaN
3,4d2ced487c3343612394d241bab83e894a8c7e1255e4a7...,2024-01,Surrey Police,Surrey Police,-0.101292,51.51477,On or near Amen Court,E01032739,City of London 001F,Other theft,Investigation complete; no suspect identified,NaN
4,7d7b66030d69eae7f5c4b544e7f9808ec0679dd7eaa956...,2024-01,Surrey Police,Surrey Police,-0.101292,51.51477,On or near Amen Court,E01032739,City of London 001F,Vehicle crime,Investigation complete; no suspect identified,NaN